index:
  handler: dist/lambda/app/app-handler.handler
  events:
    - http:
        method: any
        path: '/'
        cors: true
    - http:
        method: any
        path: '{proxy+}'
        cors: true
