
# project name
service: nest-sls-sample-project

frameworkVersion: '2'

plugins:
  - serverless-offline
#  - serverless-dynamodb-local
#  - serverless-layers

custom:
  dynamodb:
    stages: dev
    start:
      port: 8000
      inMemory: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1
  profile: default
  iam:
    role: fake-role

  deploymentBucket:
    name: fake-bucket

  environment:
    DYNAMODB_TABLE:

functions: ${file(./src/config/functions.yaml)}

resources:
  - ${file(./src/db/nosql/dynamodb/dynamodb.yaml)}

package:
  individually: true
